### PR TITLE
Improvement/implement vanilla node js test runner

### PR DESCRIPTION
**Pull request by Aaron9174**
I use this plugin in obsidian and wanted to continue to maintain it. I haven't really done open source development but have 6 years experience in a professional setting (web development + embedded development). Anyways, was interested in Nodes vanilla testing system which seems to have reach stable status in Node 22. So, here's the first PR, I am still working through the code coverage on the utils file, but wanted to put this out here to get eyes on it. The scope of this PR is to get a testing framework implemented, and finish the testing of the utils file.

### CODE REVIEW

**Comment by ennioitaliano** [comment]
Hi, and thank you so much for the PR! It's been some time since I last touched this project, and I'm neither proficient in TypeScript nor in tests. By the way, I asked a colleague of mine to look at your code, and he said it's ok, so I'll approve it. Before merging, please try to work on the TODOs you left. Thank you again!

**Review by ennioitaliano — APPROVED** [review]

**Comment by Aaron9174** [comment]
Excellent and nice to meet you!

This will be the first of many PRs to get this repository firmly unit tested, with the initial goal of 95% code coverage. This PR is scoped to just get the framework + an initial test file for something in source tested with happy day cases. I was originally planning on adding TODOs as I go and will return in a final PR to snip up the harder to hit testing errors for the happy day cases. Still, I'll look into those TODOs and see if I can get them resolved.

At some point, error handling cases will need to be added but that's a lot of overhead at the moment, I just want the success cases so when I go to make meaningful source changes, I know I'm not breaking anything.

I'll also be building this and running it in my local obsidian repo as a form of manual integration test before pushing this in. Will let you know if I run into any problems there.

Looking forward to working with you, and excited about open source development.

**Comment by ennioitaliano** [comment]
Ok, let me know when you think this PR can be merged. And by the way, for the next time [sign your commits](https://docs.github.com/authentication/managing-commit-signature-verification/about-commit-signature-verification) if possible.

**Comment by Aaron9174** [comment]
As an update, having no success this week on getting the c8 code coverage tool to cover my lines correctly, thrown away my work multiple times in different attempts, eventually I will land on something that works. Putting that aside for now and looking at other todos. It does say that merging is blocked until all commits are signed, do I need to rebase the history with signed history?

**Comment by Aaron9174** [comment]
https://dev.to/stroiman/writing-an-obsidian-plugin-driven-by-tests-1b35
Was trying to use Node test runner mock system, but it wasn't robust enough so installed sinon. Ran into issues testing yet again since obsidian is a closed package, meaning we only have access to the types. See this article:
https://dev.to/stroiman/writing-an-obsidian-plugin-driven-by-tests-1b35
For more information. Just keeping the information related to this effort consolidated to this PR comment thread, not sure if there is a better place for comments like this, but we. still got a bit of a ways to go with this before it's in a good enough spot to merge.

**Comment by ennioitaliano** [comment]
> It does say that merging is blocked until all commits are signed, do I need to rebase the history with signed history?

No I will merge it manually when you tell me the PR is ready to do so 👍 thank you again for your effort

**Comment by Aaron9174** [comment]
Ended up rebasing with signed commits anyways so all that should be in order now. I have landed on a design that is functional and reduces some of the overhead for testing. Essentially, interfaces that contain a subset of the functionality of the obsidian interfaces will be used in source, these interfaces will then be implemented in mock concrete mock classes whose only purpose will be to be mocked out by sinon itself (since you need a concrete class to take advantage of sinons mocking API). Some notes of this design:

- The interfaces are subsets and don't just extend the obsidian interfaces because we really only care about the implementation that our source code will use
   - This means we force obsidian to conform to our interface that we have control over, rather than being forced to implement some really long interface (like Vault)
   - Rather than breaking our code _every_ time the API changes (if we just implemented the type directly in our concrete mock classes), our code will now only break when changes to API that concerns our code changes
- We can now mock out the mock objects as we see fit

**Comment by Aaron9174** [comment]
Alright, I think this PR is finished up for now. Only one TODO which is some branch not covered in the sort files util function, will re-visit this in future PRs.

**Comment by ennioitaliano** [comment]
Merged, thank you again 😀

**Pull request merged**
